### ISSUE TITLE
Login PI 3 adding custom applications - Walkthrough - Ferry's Techsite

### ISSUE THREAD

**Issue by fstelte** [fstelte/fstelte.github.io#4]
https://tech.stelte.nl/post/login-pi-3-adding-custom-applications/ 

 In my previous blog about Login PI3 I showed how to install and configure Login PI 3. In this blog I will show you how to create new applications in Login PI 3 and will show you how to add basic steps for that application. In this article I will use SumatraPDF (because it is my favorite PDF viewer) as an example, you can replace SumtraPDF with your own application as wanted.

**Comment by cybercondoom** [comment]
This is a test
